package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"
	"jet/ent"
	graphql1 "jet/graphql"
	"time"
)

// ID is the resolver for the id field.
func (r *customerResolver) ID(ctx context.Context, obj *ent.Customer) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Name is the resolver for the name field.
func (r *customerResolver) Name(ctx context.Context, obj *ent.Customer) (string, error) {
	panic(fmt.Errorf("not implemented: Name - name"))
}

// Gender is the resolver for the gender field.
func (r *customerResolver) Gender(ctx context.Context, obj *ent.Customer) (ent.CustomerGender, error) {
	panic(fmt.Errorf("not implemented: Gender - gender"))
}

// Dob is the resolver for the dob field.
func (r *customerResolver) Dob(ctx context.Context, obj *ent.Customer) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: Dob - dob"))
}

// Customer returns graphql1.CustomerResolver implementation.
func (r *Resolver) Customer() graphql1.CustomerResolver { return &customerResolver{r} }

type customerResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *customerResolver) CitizenID(ctx context.Context, obj *ent.Customer) (string, error) {
	panic(fmt.Errorf("not implemented: CitizenID - citizenId"))
}
func (r *customerResolver) Phone(ctx context.Context, obj *ent.Customer) (string, error) {
	panic(fmt.Errorf("not implemented: Phone - phone"))
}
func (r *customerResolver) Address(ctx context.Context, obj *ent.Customer) (string, error) {
	panic(fmt.Errorf("not implemented: Address - address"))
}
func (r *customerResolver) CreatedAt(ctx context.Context, obj *ent.Customer) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}
func (r *customerResolver) UpdatedAt(ctx context.Context, obj *ent.Customer) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}
